name: wijha
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.23.0+1
  salomon_bottom_bar: ^3.2.0
  carousel_slider: ^4.0.0
  tab_container: ^1.2.0
  google_maps_flutter: ^2.1.1
  http: ^0.13.4
  flutter_polyline_points: ^1.0.0
  provider: ^6.0.2
  dio: ^4.0.6
  image_picker:
  snippet_coder_utils: ^1.0.10
  syncfusion_flutter_datepicker: ^19.4.53
  flutter_datetime_picker: ^1.5.1
  day_night_time_picker: ^1.0.5
  flutter_tags: ^1.0.0-nullsafety.1
  search_choices: ^2.0.19
  qr_flutter: ^4.0.0
  im_stepper: ^0.1.3
  step_progress_indicator: ^1.0.2
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  device_preview: ^1.0.0
  flutter_vector_icons: ^1.0.0
  flutter_screenutil: ^5.3.1
  animated_theme_switcher: ^2.0.6
  line_awesome_flutter: ^2.0.0
  favorite_button: ^0.0.4
  lint: ^1.8.2
  json_annotation: '>=4.5.0'

  #  games_services: ^2.0.7

    # format date time
  intl: ^0.17.0
  carousel_images: ^1.1.2
  multi_select_flutter: ^4.1.2
  multiselect_formfield: ^0.1.7
  qr_code_scanner: ^0.7.0
  flutter_rating_bar: ^4.0.0
  comment_box: ^0.0.17
  introduction_screen: ^3.0.2
  permission_handler: ^9.2.0
  riverpod: ^1.0.3
  flutter_riverpod: ^1.0.3
  firebase_auth: ^3.0.2
  firebase_core: ^1.5.0
  encrypt: ^5.0.1
  crypto: ^3.0.2
  cloud_firestore:

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  json_serializable: 

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/wijhaLogo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/images/tours/

  uses-material-design: true

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300

        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400

        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700

        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
