name: Testing the Django API

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_tests:
    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      MONGO_HOST: ${{ secrets.MONGO_HOST }}
      MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      # Setup .env file for secrets access
      - name: Create env file
        run: |
          touch .env
          echo DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} >> .env
          echo MONGO_HOST=${{ secrets.MONGO_HOST }} >> .env
          echo MONGO_DATABASE=${{ secrets.MONGO_DATABASE }} >> .env
          cat .env
      - name: Install requirements
        run: |
          pip install pipenv
          pipenv lock -r > requirements.txt
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python manage.py test
